services:
  - type: web
    name: ai-careerhub-backend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run seed-admin
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
